apiVersion: v1
kind: Pod
metadata:
  name: hello-python
  app: hello
  labels:
    # tags.datadoghq.com/env: "prod"
    # tags.datadoghq.com/service: "hello-python"
    # tags.datadoghq.com/version: "1.0"
spec:
  containers:
  - name: hello-python
    image: leopaillier/hello-python:1.0
    imagePullPolicy: Always
    ports:
    - containerPort: 5000
    # env:
    # - name: DD_AGENT_HOST
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: status.hostIP
    # - name: DD_ENV
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: metadata.labels['tags.datadoghq.com/env']
    # - name: DD_VERSION
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: metadata.labels['tags.datadoghq.com/version']
    # - name: DD_LOGS_INJECTION
    #   value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
spec:
  selector:
    app: hello
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000